name: Deploy To Production

on:
  pull_request:
    branches:
      - main
    # Trigger when the develop-to-main PR is automatically closed by a PR merge
    types: [closed]

jobs:
  deploy:
    name: Deploy To Render
    # Only run if the PR was closed by an actual merge (not an unwanted PR)
    # Ensure the PR is merged and the source branch is 'develop'
    if: github.event.pull_request.merged == true && github.event.pull_request.head.ref == 'develop'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install

      - name: Deploy
        # The branch should be correct at this point, but it's good to have this
        # positive check
        if: github.ref == 'refs/heads/main'
        env:
          DEPLOY_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$DEPLOY_URL"
