name: Deploy To Production

on:
    pull_request:
      branches:
        - main
      types: [closed]   # Trigger when PR is closed (by a PR merge)
 
jobs:
  from-dev-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check is PR source from develop branch
        run: |
          if [ "${{ github.head_ref }}" != "develop" ]; then
            echo "Error: PR must come from the 'develop' branch." && exit 1;
          fi

  deploy:
    if: github.event.pull_request.merged == true  # Only run if the PR was merged
    runs-on: ubuntu-latest
    steps:
        - name: Checkout source
          uses: actions/checkout@v3

        - name: Test
          run: |
            npm install
            npm run test

        - name: Deploy
          if: github.ref == 'refs/heads/main'
          env:
            DEPLOY_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
          run: |
            curl "$DEPLOY_URL"
   